/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bmw-m1.glb -T -k -s -o BMW-M1.tsx 
Files: bmw-m1.glb [7.25MB] > /Users/mikejin/Documents/Github/macbook-gsap-landing-page/public/models/bmw-m1-transformed.glb [1.1MB] (85%)
Author: D3DARTM (https://sketchfab.com/D3DARTM)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ac-bmw-1m-free-f0ac8fa9bf1e4d79a03a4a3ea6d24afa
Title: AC - Bmw 1m [FREE]
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    WHEEL_RR_RT_Battistrada_0: THREE.Mesh
    WHEEL_RR_RT_rim_0: THREE.Mesh
    WHEEL_RR_LOGHI_RIM_0: THREE.Mesh
    polymsh266_SUB6_INT_Cromato_0: THREE.Mesh
    polymsh266_SUB3_INT_Plaastica_NERA_0: THREE.Mesh
    polymsh266_SUB1_INT_Skin_0: THREE.Mesh
    polymsh266_SUB2_INT_Velluto_0: THREE.Mesh
    polymsh266_SUB4_LIVREA_0: THREE.Mesh
    polymsh266_SUB7_INT_Gomma_0: THREE.Mesh
    polymsh266_SUB9_INT_Speakers_0: THREE.Mesh
    polymsh266_SUB8_INT_Plaastica_Opaca_0: THREE.Mesh
    polymsh266_SUB5_INT_Door_Grid_0: THREE.Mesh
    polymsh266_SUB0_INT_Cuciture_skinned_0: THREE.Mesh
    polymsh_detached29_SUB2_MIRROR_0: THREE.Mesh
    polymsh_detached29_SUB3_VETRI_Fanali_0: THREE.Mesh
    polymsh_detached29_SUB0_PLASTICA_Nera_lucida_0: THREE.Mesh
    polymsh73_SUB0_CAR_PinzaFreni_0: THREE.Mesh
    polymsh73_SUB1_Chassis_0: THREE.Mesh
    brake_light_2_2_Fanali_POSTERIORI_TS_0: THREE.Mesh
    polymsh258_SUB2_LOGHI_normal_MAP_0: THREE.Mesh
    CINTURE_OFF_SUB0_INT_CintureSicurezza_0: THREE.Mesh
    GEO_Cambio_SUB0_INT_Display_0: THREE.Mesh
    polymsh259_SUB14_INT_VetroDisplay_0: THREE.Mesh
    polymsh259_SUB2_INT_Pedana_0: THREE.Mesh
    polymsh259_SUB9_INT_Pedali_0: THREE.Mesh
    polymsh259_SUB19_INT_Rotelline_0: THREE.Mesh
    polymsh259_SUB1_INT_Stoffa_0: THREE.Mesh
    GEO_Guaina_Cambio_SUB0_INT_Velluto_RIG_0: THREE.Mesh
    IN_rear_Glass_2_VETRI_defrost_interno_0: THREE.Mesh
    front_light_1_2_Dettaglio_Faro_0: THREE.Mesh
    polymsh262_SUB2_FANALI_Anteriori_0: THREE.Mesh
    rear_light_2_2_Fanali_POSTERIORI_OS_0: THREE.Mesh
    polymsh263_SUB2_FARI_Poseriori_EXTRA2_0: THREE.Mesh
    polymsh66_SUB3_GRIGLIA_NM_0: THREE.Mesh
    polymsh66_SUB4_GAS_CAP_NM_0: THREE.Mesh
    Geometry112_2_Dischi_Freni_0: THREE.Mesh
    polymsh65_SUB0_VETRI_Nero_0: THREE.Mesh
    polymsh65_SUB6_Chassis_METAL_0: THREE.Mesh
  }
  materials: {
    RT_Battistrada: THREE.MeshStandardMaterial
    RT_rim: THREE.MeshStandardMaterial
    LOGHI_RIM: THREE.MeshStandardMaterial
    INT_Cromato: THREE.MeshStandardMaterial
    INT_Plaastica_NERA: THREE.MeshStandardMaterial
    INT_Skin: THREE.MeshStandardMaterial
    INT_Velluto: THREE.MeshStandardMaterial
    LIVREA: THREE.MeshStandardMaterial
    INT_Gomma: THREE.MeshStandardMaterial
    INT_Speakers: THREE.MeshStandardMaterial
    INT_Plaastica_Opaca: THREE.MeshStandardMaterial
    INT_Door_Grid: THREE.MeshStandardMaterial
    INT_Cuciture_skinned: THREE.MeshStandardMaterial
    MIRROR: THREE.MeshStandardMaterial
    VETRI_Fanali: THREE.MeshPhysicalMaterial
    PLASTICA_Nera_lucida: THREE.MeshStandardMaterial
    CAR_PinzaFreni: THREE.MeshStandardMaterial
    Chassis: THREE.MeshStandardMaterial
    Fanali_POSTERIORI_TS: THREE.MeshStandardMaterial
    LOGHI_normal_MAP: THREE.MeshStandardMaterial
    INT_CintureSicurezza: THREE.MeshStandardMaterial
    INT_Display: THREE.MeshStandardMaterial
    INT_VetroDisplay: THREE.MeshStandardMaterial
    INT_Pedana: THREE.MeshStandardMaterial
    INT_Pedali: THREE.MeshStandardMaterial
    INT_Rotelline: THREE.MeshStandardMaterial
    INT_Stoffa: THREE.MeshStandardMaterial
    INT_Velluto_RIG: THREE.MeshStandardMaterial
    VETRI_defrost_interno: THREE.MeshStandardMaterial
    Dettaglio_Faro: THREE.MeshStandardMaterial
    FANALI_Anteriori: THREE.MeshStandardMaterial
    Fanali_POSTERIORI_OS: THREE.MeshStandardMaterial
    FARI_Poseriori_EXTRA2: THREE.MeshStandardMaterial
    GRIGLIA_NM: THREE.MeshStandardMaterial
    GAS_CAP_NM: THREE.MeshStandardMaterial
    Dischi_Freni: THREE.MeshStandardMaterial
    VETRI_Nero: THREE.MeshStandardMaterial
    Chassis_METAL: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function BMW_M1_Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/bmw-m1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="WHEEL_RR_RT_Battistrada_0" castShadow receiveShadow geometry={nodes.WHEEL_RR_RT_Battistrada_0.geometry} material={materials.RT_Battistrada} position={[-0.877, 0.389, -1.559]} scale={0.012} />
      <mesh name="WHEEL_RR_RT_rim_0" castShadow receiveShadow geometry={nodes.WHEEL_RR_RT_rim_0.geometry} material={materials.RT_rim} position={[-0.877, 0.389, -1.559]} scale={0.012} />
      <mesh name="WHEEL_RR_LOGHI_RIM_0" castShadow receiveShadow geometry={nodes.WHEEL_RR_LOGHI_RIM_0.geometry} material={materials.LOGHI_RIM} position={[-0.877, 0.389, -1.559]} scale={0.012} />
      <mesh name="polymsh266_SUB6_INT_Cromato_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB6_INT_Cromato_0.geometry} material={materials.INT_Cromato} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB3_INT_Plaastica_NERA_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB3_INT_Plaastica_NERA_0.geometry} material={materials.INT_Plaastica_NERA} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB1_INT_Skin_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB1_INT_Skin_0.geometry} material={materials.INT_Skin} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB2_INT_Velluto_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB2_INT_Velluto_0.geometry} material={materials.INT_Velluto} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB4_LIVREA_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB4_LIVREA_0.geometry} material={materials.LIVREA} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB7_INT_Gomma_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB7_INT_Gomma_0.geometry} material={materials.INT_Gomma} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB9_INT_Speakers_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB9_INT_Speakers_0.geometry} material={materials.INT_Speakers} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB8_INT_Plaastica_Opaca_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB8_INT_Plaastica_Opaca_0.geometry} material={materials.INT_Plaastica_Opaca} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB5_INT_Door_Grid_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB5_INT_Door_Grid_0.geometry} material={materials.INT_Door_Grid} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh266_SUB0_INT_Cuciture_skinned_0" castShadow receiveShadow geometry={nodes.polymsh266_SUB0_INT_Cuciture_skinned_0.geometry} material={materials.INT_Cuciture_skinned} position={[0.957, 0.99, 0.82]} scale={0.012} />
      <mesh name="polymsh_detached29_SUB2_MIRROR_0" castShadow receiveShadow geometry={nodes.polymsh_detached29_SUB2_MIRROR_0.geometry} material={materials.MIRROR} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="polymsh_detached29_SUB3_VETRI_Fanali_0" castShadow receiveShadow geometry={nodes.polymsh_detached29_SUB3_VETRI_Fanali_0.geometry} material={materials.VETRI_Fanali} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="polymsh_detached29_SUB0_PLASTICA_Nera_lucida_0" castShadow receiveShadow geometry={nodes.polymsh_detached29_SUB0_PLASTICA_Nera_lucida_0.geometry} material={materials.PLASTICA_Nera_lucida} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="polymsh73_SUB0_CAR_PinzaFreni_0" castShadow receiveShadow geometry={nodes.polymsh73_SUB0_CAR_PinzaFreni_0.geometry} material={materials.CAR_PinzaFreni} position={[-0.874, 0.388, -1.559]} scale={0.012} />
      <mesh name="polymsh73_SUB1_Chassis_0" castShadow receiveShadow geometry={nodes.polymsh73_SUB1_Chassis_0.geometry} material={materials.Chassis} position={[-0.874, 0.388, -1.559]} scale={0.012} />
      <mesh name="brake_light_2_2_Fanali_POSTERIORI_TS_0" castShadow receiveShadow geometry={nodes.brake_light_2_2_Fanali_POSTERIORI_TS_0.geometry} material={materials.Fanali_POSTERIORI_TS} scale={0.012} />
      <mesh name="polymsh258_SUB2_LOGHI_normal_MAP_0" castShadow receiveShadow geometry={nodes.polymsh258_SUB2_LOGHI_normal_MAP_0.geometry} material={materials.LOGHI_normal_MAP} position={[0.422, 0.999, 0.32]} rotation={[0.384, 0, 0]} scale={0.012} />
      <mesh name="CINTURE_OFF_SUB0_INT_CintureSicurezza_0" castShadow receiveShadow geometry={nodes.CINTURE_OFF_SUB0_INT_CintureSicurezza_0.geometry} material={materials.INT_CintureSicurezza} scale={0.012} />
      <mesh name="GEO_Cambio_SUB0_INT_Display_0" castShadow receiveShadow geometry={nodes.GEO_Cambio_SUB0_INT_Display_0.geometry} material={materials.INT_Display} position={[-0.009, 0.624, 0.188]} scale={0.012} />
      <mesh name="polymsh259_SUB14_INT_VetroDisplay_0" castShadow receiveShadow geometry={nodes.polymsh259_SUB14_INT_VetroDisplay_0.geometry} material={materials.INT_VetroDisplay} scale={0.012} />
      <mesh name="polymsh259_SUB2_INT_Pedana_0" castShadow receiveShadow geometry={nodes.polymsh259_SUB2_INT_Pedana_0.geometry} material={materials.INT_Pedana} scale={0.012} />
      <mesh name="polymsh259_SUB9_INT_Pedali_0" castShadow receiveShadow geometry={nodes.polymsh259_SUB9_INT_Pedali_0.geometry} material={materials.INT_Pedali} scale={0.012} />
      <mesh name="polymsh259_SUB19_INT_Rotelline_0" castShadow receiveShadow geometry={nodes.polymsh259_SUB19_INT_Rotelline_0.geometry} material={materials.INT_Rotelline} scale={0.012} />
      <mesh name="polymsh259_SUB1_INT_Stoffa_0" castShadow receiveShadow geometry={nodes.polymsh259_SUB1_INT_Stoffa_0.geometry} material={materials.INT_Stoffa} scale={0.012} />
      <mesh name="GEO_Guaina_Cambio_SUB0_INT_Velluto_RIG_0" castShadow receiveShadow geometry={nodes.GEO_Guaina_Cambio_SUB0_INT_Velluto_RIG_0.geometry} material={materials.INT_Velluto_RIG} scale={0.012} />
      <mesh name="IN_rear_Glass_2_VETRI_defrost_interno_0" castShadow receiveShadow geometry={nodes.IN_rear_Glass_2_VETRI_defrost_interno_0.geometry} material={materials.VETRI_defrost_interno} scale={0.012} />
      <mesh name="front_light_1_2_Dettaglio_Faro_0" castShadow receiveShadow geometry={nodes.front_light_1_2_Dettaglio_Faro_0.geometry} material={materials.Dettaglio_Faro} scale={0.012} />
      <mesh name="polymsh262_SUB2_FANALI_Anteriori_0" castShadow receiveShadow geometry={nodes.polymsh262_SUB2_FANALI_Anteriori_0.geometry} material={materials.FANALI_Anteriori} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="rear_light_2_2_Fanali_POSTERIORI_OS_0" castShadow receiveShadow geometry={nodes.rear_light_2_2_Fanali_POSTERIORI_OS_0.geometry} material={materials.Fanali_POSTERIORI_OS} scale={0.012} />
      <mesh name="polymsh263_SUB2_FARI_Poseriori_EXTRA2_0" castShadow receiveShadow geometry={nodes.polymsh263_SUB2_FARI_Poseriori_EXTRA2_0.geometry} material={materials.FARI_Poseriori_EXTRA2} scale={0.012} />
      <mesh name="polymsh66_SUB3_GRIGLIA_NM_0" castShadow receiveShadow geometry={nodes.polymsh66_SUB3_GRIGLIA_NM_0.geometry} material={materials.GRIGLIA_NM} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="polymsh66_SUB4_GAS_CAP_NM_0" castShadow receiveShadow geometry={nodes.polymsh66_SUB4_GAS_CAP_NM_0.geometry} material={materials.GAS_CAP_NM} position={[0, 0.165, 0]} scale={0.012} />
      <mesh name="Geometry112_2_Dischi_Freni_0" castShadow receiveShadow geometry={nodes.Geometry112_2_Dischi_Freni_0.geometry} material={materials.Dischi_Freni} position={[-0.874, 0.388, 1.537]} scale={0.012} />
      <mesh name="polymsh65_SUB0_VETRI_Nero_0" castShadow receiveShadow geometry={nodes.polymsh65_SUB0_VETRI_Nero_0.geometry} material={materials.VETRI_Nero} scale={0.012} />
      <mesh name="polymsh65_SUB6_Chassis_METAL_0" castShadow receiveShadow geometry={nodes.polymsh65_SUB6_Chassis_METAL_0.geometry} material={materials.Chassis_METAL} scale={0.012} />
    </group>
  )
}

useGLTF.preload('/models/bmw-m1-transformed.glb')
