/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-16.glb -T -k -s -o Macbook-16.tsx 
Files: macbook-16.glb [639.28KB] > /Users/mikejin/Documents/Github/macbook-gsap-landing-page/public/models/macbook-16-transformed.glb [629.72KB] (1%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/


import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import useMacbookStore from '@/store'
import { noChangeParts } from '@/constants'
import { Color } from 'three'
import { useEffect } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh
    Object_16: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_38: THREE.Mesh
    Object_42: THREE.Mesh
    Object_48: THREE.Mesh
    Object_54: THREE.Mesh
    Object_58: THREE.Mesh
    Object_66: THREE.Mesh
    Object_74: THREE.Mesh
    Object_82: THREE.Mesh
    Object_96: THREE.Mesh
    Object_107: THREE.Mesh
    Object_123: THREE.Mesh
    Object_127: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    zhGRTuGrQoJflBD: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    lmWQsEjxpsebDlK: THREE.MeshStandardMaterial
    LtEafgAVRolQqRw: THREE.MeshStandardMaterial
    iyDJFXmHelnMTbD: THREE.MeshStandardMaterial
    eJObPwhgFzvfaoZ: THREE.MeshStandardMaterial
    nDsMUuDKliqGFdU: THREE.MeshStandardMaterial
    CRQixVLpahJzhJc: THREE.MeshStandardMaterial
    YYwBgwvcyZVOOAA: THREE.MeshStandardMaterial
    SLGkCohDDelqXBu: THREE.MeshStandardMaterial
    WnHKXHhScfUbJQi: THREE.MeshStandardMaterial
    fNHiBfcxHUJCahl: THREE.MeshStandardMaterial
    LpqXZqhaGCeSzdu: THREE.MeshStandardMaterial
    gMtYExgrEUqPfln: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    JvMFZolVCdpPqjj: THREE.MeshStandardMaterial
    sfCQkHOWyrsLmor: THREE.MeshStandardMaterial
    ZCDwChwkbBfITSW: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function MacbookModel16(props: JSX.IntrinsicElements['group']) {
  const { color } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/macbook-16-transformed.glb') as GLTFResult
  const texture = useTexture('screen.png');

  useEffect(() => {
    scene.traverse((child) =>{
      if(child.isMesh) {
        // Change color only if the part name is NOT noChangeParts
        if(!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    })
  }, [color, scene])
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_10" castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_16" castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_20" castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_22" castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_30" castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_32" castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_34" castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_38" castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_42" castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_48" castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_54" castShadow receiveShadow geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_58" castShadow receiveShadow geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_66" castShadow receiveShadow geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_74" castShadow receiveShadow geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_82" castShadow receiveShadow geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_96" castShadow receiveShadow geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_107" castShadow receiveShadow geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_123" castShadow receiveShadow geometry={nodes.Object_123.geometry} material={materials.sfCQkHOWyrsLmor} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh name="Object_127" castShadow receiveShadow geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/macbook-16-transformed.glb')
